---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-cm
  namespace: zabbix
  labels:
    app.kubernetes.io/name: nginx-conf-cm
data:
  nginx.conf: |-
    log_format ltsv 'time:$time_iso8601\t'
                    'host:$host\t'
                    'http_host:$http_host\t'
                    'scheme:$scheme\t'
                    'remote_addr:$remote_addr\t'
                    'remote_user:$remote_user\t'
                    'request:$request\t'
                    'status:$status\t'
                    'bytes_sent:$bytes_sent\t'
                    'body_bytes_sent:$body_bytes_sent\t'
                    'http_referer:$http_referer\t'
                    'http_user_agent:$http_user_agent\t'
                    'http_x_forwarded_for:$http_x_forwarded_for\t'
                    'http_x_forwarded_proto:$http_x_forwarded_proto\t'
                    'sent_http_cache_control:$sent_http_cache_control\t'
                    'request_time:$request_time\t'
                    'upstream_response_time:$upstream_response_time\t'
                    'msec:$msec\t'
                    'upstream_http_content_type:$upstream_http_content_type\t'
                    'connection:$connection';

    server {
        listen 8080;
        listen [::]:8080;

        server_name     zabbix;
        index           index.php;

        access_log /dev/fd/1 ltsv;
        error_log       /dev/fd/2 notice;

        set $webroot '/usr/share/zabbix';

        root $webroot;

        large_client_header_buffers 8 8k;
        client_max_body_size 10M;

        location = /favicon.ico {
            log_not_found off;
        }

        location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
        }

        # Deny all attempts to access hidden files such as .htaccess, .htpasswd, .DS_Store (Mac).
        location ~ /\. {
            deny all;
            access_log off;
            log_not_found off;
        }

        # caching of files
        location ~* \.ico$ {
            expires 1y;
        }

        location ~* \.(js|css|png|jpg|jpeg|gif|xml|txt)$ {
            expires 14d;
        }

        location ~ /(app\/|conf[^\.]|include\/|local\/|locale\/) {
            deny all;
            return 404;
        }

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ .php$ {
            fastcgi_pass   unix:/tmp/php-fpm.sock;
            fastcgi_index  index.php;

            fastcgi_param  SCRIPT_FILENAME  $webroot$fastcgi_script_name;

            include fastcgi_params;
            fastcgi_param  QUERY_STRING     $query_string;
            fastcgi_param  REQUEST_METHOD   $request_method;
            fastcgi_param  CONTENT_TYPE     $content_type;
            fastcgi_param  CONTENT_LENGTH   $content_length;
            fastcgi_intercept_errors        on;
            fastcgi_ignore_client_abort     off;
            fastcgi_connect_timeout 60;
            fastcgi_send_timeout 180;
            fastcgi_read_timeout 601;
            fastcgi_buffer_size 128k;
            fastcgi_buffers 4 256k;
            fastcgi_busy_buffers_size 256k;
            fastcgi_temp_file_write_size 256k;
        }
    }
---
