---
apiVersion: v1
kind: Namespace
metadata:
    name: zabbix
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysql-secret
  namespace: zabbix
  labels:
    app.kubernetes.io/name: mysql-secret
data:
  mysql_root_password: "cGFzc3dvcmQ="
  mysql_zabbix_user: "emFiYml4"
  mysql_zabbix_password: "emFiYml4"
---
