---
apiVersion: v1
kind: Endpoints
metadata:
  name: zabbix-statefulset-0-svc-lb
  namespace: zabbix
subsets:
  - addresses:
      - ip: 10.244.65.147
    ports:
      - port: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: zabbix-statefulset-1-svc-lb
  namespace: zabbix
subsets:
  - addresses:
      - ip: 10.244.79.129
    ports:
    ports:
      - port: 8080
---
