---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web-svc-lb
  namespace: zabbix
  labels:
    app.kubernetes.io/name: zabbix-web-svc-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: zabbix
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
---

