---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-statefulset-0-svc-lb
  namespace: zabbix
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-statefulset-1-svc-lb
  namespace: zabbix
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
