---
apiVersion: v1
kind: Endpoints
metadata:
  name: zabbix-statefulset-0-svc-lb
  namespace: zabbix
subsets:
  - addresses:
      - ip: 10.244.65.150
    ports:
      - port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-statefulset-0-svc-lb
  namespace: zabbix
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: zabbix-statefulset-1-svc-lb
  namespace: zabbix
subsets:
  - addresses:
      - ip: 10.244.79.130
    ports:
    ports:
      - port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-statefulset-1-svc-lb
  namespace: zabbix
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
